services:
  aspdotnet-project:
    image: aspdotnet-project
    build:
      context: .
      dockerfile: MovieApp.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5295:8080"
    env_file:
      - ./MovieApp.Api/.env